### ISSUE TITLE
minLevel

### ISSUE THREAD

**Issue by Ericno69** [johansatge/obsidian-automatic-table-of-contents#11]
Dear @johansatge ,
appreciated, very usefull plugin.
Do you plan to add a minLevel option to exclude the (redundant) title of the document, which is generally at the first level?
Best regards.

**Comment by RGCLine** [comment]
Hi @Ericno69 and @johansatge,

cool plugin. Such a parameter would really help and extend the current functionality in a very flexible way.

Beste Regards

**Comment by johansatge** [comment]
Done in `1.1.0` thx @ras0q ❤️
