### ISSUE TITLE
Index in a PDF

### ISSUE THREAD

**Issue by mikajed** [johansatge/obsidian-automatic-table-of-contents#12]
Thanks for this nice Plugin, I got a question, is it possible to make the index and its links clickable in a exported PDF?

It (the links) didn't work for me in the PDF.

**Comment by johansatge** [comment]
Hi!
The plugin generates Obsidian-style internal links under the hood; a title:
```md
# Some title
```
will generate the corresponding link:
```md
[[#Some title]]
```

It seems these links aren't supported yet in PDFs: [PDF export: Make links within same document functional](https://forum.obsidian.md/t/pdf-export-make-links-within-same-document-functional/16384)  
I can't find a workaround, so we'll probably have to wait for an official Obsidian update (or a dedicated plugin; reading the thread linked above, it seems some are in the work)

**Comment by mikajed** [comment]
> Hi! The plugin generates Obsidian-style internal links under the hood; a title:
> 
> ```
> # Some title
> ```
> 
> will generate the corresponding link:
> 
> ```
> [[#Some title]]
> ```
> 
> It seems these links aren't supported yet in PDFs: [PDF export: Make links within same document functional](https://forum.obsidian.md/t/pdf-export-make-links-within-same-document-functional/16384) I can't find a workaround, so we'll probably have to wait for an official Obsidian update (or a dedicated plugin; reading the thread linked above, it seems some are in the work)

Thank you very much for the information!
