### ISSUE TITLE
Failed to load plugin automatic-table-of-contents

### ISSUE THREAD

**Issue by bangsluke** [johansatge/obsidian-automatic-table-of-contents#17]
Fails when trying to enable from the Obsidian library. Able to install but the title error message appears when trying to enable the plugin

![image](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/61457009/c1e5e0b9-75b9-41c3-8265-ea43a37263c2)

**Comment by johansatge** [comment]
Thx for the report! Fixed in `1.0.5`

**Comment by bangsluke** [comment]
All fixed, thanks for fixing so quickly!
