### ISSUE TITLE
Doesn't it work on android 11?

### ISSUE THREAD

**Issue by merlinuwe** [johansatge/obsidian-automatic-table-of-contents#2]
Hi, interesting concept, but doesn't it run with android 11 yet?

**Comment by johansatge** [comment]
Hi! What behavior are you observing? I could only test on Android 13, but it should work no matter the Android version I think. (Latest Obsidian version, plugin `1.0.3`)

**Comment by johansatge** [comment]
Several issues have been solved lately, including a few that could be related to mobile - I'll go ahead and close, feel free to comment if you still reproduce with the latest version!
