### ISSUE TITLE
Conflicts with the tag summary plug-in

### ISSUE THREAD

**Issue by utopia111** [johansatge/obsidian-automatic-table-of-contents#20]
Thank you for developing this plug-in. When I use automatic-table-of-contents at the beginning of the page, the contents labeled in the following contents disappear in the tag summary. When I removed this directory, the relevant content appeared again in the label usage document statistics.

**Comment by johansatge** [comment]
Hello! I'm not sure I understood the bug, do you have an example of page to share with its raw markdown contents?

**Comment by johansatge** [comment]
Closing as old, feel free to reopen/comment if the issue can still be reproduced 🙏
