### ISSUE TITLE
Feature Request: TOC of currently focused file in Side Panel

### ISSUE THREAD

**Issue by rollingtatoo** [johansatge/obsidian-automatic-table-of-contents#21]
Simply the ability to open the dynamic ToC for the currently focused file in a dedicated section in the Side Panel.

### Pros:
- Access to table of content for any file without necessiting to add the ToC code block inside said file
- Allows to keep the ToC as easy and quick to access as possible while scrolling through the file, without needing to scroll back to the ToC to quickly reach another section of the file

**Comment by TheFermi0n** [comment]
> Simply the ability to open the dynamic ToC for the currently focused file in a dedicated section in the Side Panel.

You can already do that with built in Obsidian Outline. Check inside the `Core plugins` section of the Obsidian settings

<img width="725" alt="image" src="https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/63984668/cafe0eee-b628-4e86-810c-3ee236abd005">

**Comment by johansatge** [comment]
Thx for pointing that out 👍 closing

**Comment by rollingtatoo** [comment]
Thank you and sorry for not looking better before opening, i'm quite recent to obsidian and not so used to the process in github issues and requests as such

**Comment by rollingtatoo** [comment]
Thanks a  lot @TheFermi0n,and sorry for not looking up better before opening, i'm quite recent to obsidian and not so used to the process in github issues and requests as such
