### ISSUE TITLE
Problem with pinned notes

### ISSUE THREAD

**Issue by TheFermi0n** [johansatge/obsidian-automatic-table-of-contents#26]
If you've generated a Table of Contents (TOC), whether normal or documented, within a note and pinned that note, clicking any entry from the generated TOC will open a new tab with the location instead of navigating to the heading within the currently opened document. 

Please see the attached screen recording below:

https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/63984668/86296acc-f59f-40cb-b4ed-6f32457964f5

**Comment by AV-AER** [comment]
This is the case for any link to any header while the note is pinned. It is not an issue with the plugin, that is the way pinned notes work in Obsidian. This behaviour is similar to changing an `<a>` tag's `target` attribute to `_blank` from the default `_self`.

Demonstration can be found at [W3S](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_a_target).

**Comment by TheFermi0n** [comment]
> This is the case for any link to any header while the note is pinned.

Thank you very much for your clarification.
