### ISSUE TITLE
Ignore emojis

### ISSUE THREAD

**Issue by jerrygreen** [johansatge/obsidian-automatic-table-of-contents#30]
I like emojis in the beginning of a title, but I would like them to be stripped from the TOC because they make too much noise there:

![image](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/13215662/b8f51d33-fa56-4e60-a823-1b83da21dad4)

**Comment by johansatge** [comment]
I personnally like emojis and would like to keep them 😄 but there could be some `includeEmojis: true|false` option (default `true`)

Not sure how to efficiently target emojis though, maybe some regex to catch the right unicode.

**Comment by jerrygreen** [comment]
On the other hand, after making a snippet to make links non-underlined, I kind-of like the emoji in the list now 😅

I guess it's just weird for me seeing emoji underlined.

For emoji regex, yes, there's a package for that: https://www.npmjs.com/package/emoji-regex

If you still make such an option, I might as well try it. But currently I don't need it as much as I thought.
