### ISSUE TITLE
Quick and dirty addition of title "Table of Contents"

### ISSUE THREAD

**Issue by AlfonsoRReyes** [johansatge/obsidian-automatic-table-of-contents#32]
This is a quick and dirty addition of a **title** to the TOC plugin, like in **Typora**.

This how it the TOC block will look after the modification:
![image](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/19330646/e2315be8-2a6d-4fdd-b101-689a389515f2)

**Instructions**
1. Modify line *108*. Instead of `const` use `let`.
2. Modify line *111*. Add a level 2 heading as the title "Table of Contents" to the variable `markdown`.

Like this:

![image](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/19330646/278ced59-8da4-4533-93d1-0e6c911ac3f6)

**Comment by johansatge** [comment]
👍 see #5
