### ISSUE TITLE
Allow inlineFirstLevel to be also for another level

### ISSUE THREAD

**Issue by Gnopps** [johansatge/obsidian-automatic-table-of-contents#39]
The option `style: inlineFirstLevel` is great to show the ToC inline, instead of vertically. However, many of my notes do not contain any first level headings at all (because of styling reasons) making this option not work. Would it please be possible to make the option be either something like:
`inlineFourthLevel`
or adding another option like: `inlineLevel: 4`

**Comment by johansatge** [comment]
Thx for the feedback! Makes sense, `style: inlineFirstLevel` could follow the same rules as `style: nestedList`: look for the right level (like defaulting to level 2 when there is no 1) and also take `minLevel` into account.

**Comment by johansatge** [comment]
Fixed in `1.3.3`
