### ISSUE TITLE
Ability to create a directory of the current document in another document

### ISSUE THREAD

**Issue by Ethan-hubs** [johansatge/obsidian-automatic-table-of-contents#40]
Hello, it is a great honor to use this plug-in you developed on Obsidian.

Here I would like to propose a new idea, you can add a command to **document 1** , so that it can generate the directory of **document 2**。

In this way, confusion can be avoided when the document is written. 

For example: When I edit a document, I have two Windows open at the same time, one to show the directory framework (for example, document 1) and one to write the actual document (for example, document 2).

Thanks again!

**Comment by johansatge** [comment]
Hi!

Thanks a lot for the feedback. This feature will be considered in #4

Also for your specific use case, you could try the native [Outline](https://help.obsidian.md/Plugins/Outline) plugin, that allows you to have your document and its table of contents side by side:

![CleanShot 2024-04-20 at 12 21 24@2x](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/5699295/2da09d31-893c-4308-b2b5-543019aa0e65)
