### ISSUE TITLE
What about a title? And configure the size of the border?

### ISSUE THREAD

**Issue by agnoldo** [johansatge/obsidian-automatic-table-of-contents#5]
Dear @johansatge , thanks for the implementation. Very good, works perfectly when exported to PDF. Amazing!

I was wondering: what do you think about adding a parameter to allow the user to define a title? It would turn into a self-contained block.

And what about configuring the size of the border? Right now the block of the TOC has a thick border so, when I add a title before it, the visual is a little strange.

Nonetheless, congratulations and thank you again!

**Comment by johansatge** [comment]
Hello! Thanks for your feedback!

- Version `1.3.0` now has a `title` option
- About the border, the plugin comes with no styles, so I assume it's your theme that is adding the border? If so it can probably be tweaked with some CSS.

Closing, but feel free to reach out if I'm mistaken about the 2nd point
