### ISSUE TITLE
README file has to be uppercase

### ISSUE THREAD

**Issue by DavideWiest** [johansatge/obsidian-automatic-table-of-contents#7]
Otherwise, as right now, the readme wont be shown in obsidian: This plugin did not provide a README file.

**Comment by johansatge** [comment]
Thanks! Fixed in `1.0.3`

![CleanShot 2023-09-30 at 10 23 46@2x](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/5699295/2a3be962-65a8-45e1-986f-e64a570cc38d)
